-- Drop view
DROP VIEW IF EXISTS CostoOrdinazioni CASCADE;

-- Drop tables
DROP TABLE IF EXISTS Pratica CASCADE;
DROP TABLE IF EXISTS Barca CASCADE;
DROP TABLE IF EXISTS Pescatore CASCADE;
DROP TABLE IF EXISTS MetodoDiPesca CASCADE;
DROP TABLE IF EXISTS Via CASCADE;
DROP TABLE IF EXISTS Zona CASCADE;
DROP TABLE IF EXISTS Citta CASCADE;
DROP TABLE IF EXISTS Bundle CASCADE;
DROP TABLE IF EXISTS Ordinazione CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Telefono CASCADE;
DROP TABLE IF EXISTS CartaPagamento CASCADE;
DROP TABLE IF EXISTS Rider CASCADE;

-- Drop functions used by triggers
DROP FUNCTION IF EXISTS almeno_una_pratica() CASCADE;
DROP FUNCTION IF EXISTS calcola_quantita_bundle() CASCADE;
DROP FUNCTION IF EXISTS controllo_copertura_rider() CASCADE;
DROP FUNCTION IF EXISTS controllo_possesso_carta_di_pagamento() CASCADE;

-- Drop domain
DROP DOMAIN IF EXISTS PWD CASCADE;
